### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by dbrgn**
- Add logo
- Create docs
- Move log and makefile to root dir

### CODE REVIEW

**Comment by Luz** [comment]
`https://raw.githubusercontent.com/dbrgn/hexdino/master/logo.svg`
shouldn't that be relative to the project directory?
and can you make the logo 128x128? should be enough imo, what do you think?

**Comment by dbrgn** [comment]
> shouldn't that be relative to the project directory?

I'm not sure if it gets rendered correctly if it's relative to the directory. It would only work if Github does some image rewriting magic. This way it'll work for sure.

> and can you make the logo 128x128? should be enough imo, what do you think?

I'd make the size 256x256 but add image compressions (e.g. reduced colors). What about that?

Compression reduces the image size without harming the quality, but reducing the resolution reduces the flexibility of how you use the logo.

**Comment by Luz** [comment]
I see no purpose to use png over svg, btw. why this png is necessary anyway?

**Comment by dbrgn** [comment]
Because if you link to https://raw.githubusercontent.com/dbrgn/hexdino/master/src/logo.svg you get text, not image data (due to server settings by Github). Therefore a HTML page won't render the SVG because it's sent with the wrong content-type.

**Comment by Luz** [comment]
Ok I need to rewrite my question: Why is the svg-link necessary anyway?
If i want to preview the logo in my browser I can also go to: https://github.com/Luz/hexdino/blob/master/src/logo.svg

**Comment by dbrgn** [comment]
In the rust docs:

``` bash
$ cargo doc
$ firefox target/doc/hexdino/index.html
```

img

**Pull request merged**
